/**                                      -*- mode:C++ -*- */

/***********************         DO NOT EDIT        ******************************
*
* SiteVisitorByID.h - Transient header for ULAM //gcnl:SymbolClass.cpp:750
*
**********************************************************************************
* This code is generated by the ULAM programming language compilation system.
*
* The ULAM programming language compilation system is free software:
* you can redistribute it and/or modify it under the terms of the GNU
* General Public License as published by the Free Software
* Foundation, either version 3 of the License, or (at your option)
* any later version.
*
* The ULAM programming language compilation system is distributed in
* the hope that it will be useful, but WITHOUT ANY WARRANTY; without
* even the implied warranty of MERCHANTABILITY or FITNESS FOR A
* PARTICULAR PURPOSE.  See the GNU General Public License for more
* details.
*
* You should have received a copy of the GNU General Public License
* along with the ULAM programming language compilation system
* software.  If not, see <http://www.gnu.org/licenses/>.
*
* @license GPL-3.0+ <http://spdx.org/licenses/GPL-3.0+>
*/

#ifndef UN_10411209215SITEVISITORBYID10_H
#define UN_10411209215SITEVISITORBYID10_H

#include "UlamDefs.h"
#include "Un_10411209215SiteVisitorByID10_Types.h"
//Forward Defs of other classes: //gcnl:SymbolTableOfClasses.cpp:576
namespace MFM { template <class EC> struct Uq_10106UrSelf10; }  //FORWARD
namespace MFM { template <class EC> struct Ue_10106Primer10; }  //FORWARD
namespace MFM { template <class EC> struct Uq_10106Random10; }  //FORWARD
namespace MFM { template <class EC> struct Uq_10109211EventWindow10; }  //FORWARD
namespace MFM { template <class EC> struct Uq_10104Cell10; }  //FORWARD
namespace MFM { template <class EC> struct Uq_10109212DecisionTree10; }  //FORWARD
namespace MFM { template <class EC> struct Ue_102564Gene10; }  //FORWARD
namespace MFM { template <class EC> struct Ue_10105Empty10; }  //FORWARD
namespace MFM { template <class EC> struct Uq_1010919AtomUtils10; }  //FORWARD
namespace MFM { template <class EC> struct Uq_10104Fail10; }  //FORWARD
namespace MFM { template <class EC> struct Uq_10105MDist10; }  //FORWARD
namespace MFM { template <class EC> struct Uq_102323C2D10; }  //FORWARD
namespace MFM { template <class EC> struct Uq_10109210ColorUtils10; }  //FORWARD
namespace MFM { template <class EC> struct Ue_102717Nucleus10; }  //FORWARD
namespace MFM { template <class EC> struct Un_10412489213WindowScanner10; }  //FORWARD
namespace MFM { template <class EC> struct Uq_10109211ClusterByID10; }  //FORWARD
namespace MFM { template <class EC> struct Uq_1010919SiteUtils10; }  //FORWARD
namespace MFM { template <class EC> struct Ue_102188EggShell10; }  //FORWARD
namespace MFM { template <class EC> struct Uq_10109210DebugUtils10; }  //FORWARD
namespace MFM { template <class EC> struct Uq_10109211SiteVisitor10; }  //FORWARD
namespace MFM { template <class EC> struct Un_102329211OutOfBounds10; }  //FORWARD
namespace MFM { template <class EC> struct Un_1035449217SiteVisitorByType10; }  //FORWARD

namespace MFM{

  template<class EC>
  class Un_10411209215SiteVisitorByID10 : public UlamTransient<EC>  /*, Uq_10109211SiteVisitor10 */  {
    // Extract short names for parameter types
    typedef typename EC::ATOM_CONFIG AC;
    typedef typename AC::ATOM_TYPE T;
    enum { BPA = AC::BITS_PER_ATOM };

    typedef BitVector<BPA> BV; //gcnl:NodeBlockClass.cpp:1621
    typedef BitField<BitVector<BPA>, VD::BITS, T::ATOM_FIRST_STATE_BIT, 0> BFTYP; //gcnl:NodeBlockClass.cpp:1624


  public:

    Un_10411209215SiteVisitorByID10(); //gcnl:NodeBlockClass.cpp:1508
    ~Un_10411209215SiteVisitorByID10(); //gcnl:NodeBlockClass.cpp:1513

    static Un_10411209215SiteVisitorByID10 THE_INSTANCE; //gcnl:NodeBlockClass.cpp:1519

//! SiteVisitorByID.ulam:13: 	typedef EventWindow.SiteNum SiteNum;

//! SiteVisitorByID.ulam:14: 	AtomUtils au;
    typedef Uq_1010919AtomUtils10<EC> Ut_Um_2au; //offset 0u //gcnl:NodeVarDeclDM.cpp:1065

//! SiteVisitorByID.ulam:15: 	EventWindow ew;
    typedef Uq_10109211EventWindow10<EC> Ut_Um_2ew; //offset 0u //gcnl:NodeVarDeclDM.cpp:1065

//! SiteVisitorByID.ulam:17: 	typedef Gene.Seqno Seqno;

//! SiteVisitorByID.ulam:18: 	typedef Cell.ID ID;

//! SiteVisitorByID.ulam:19: 	typedef Unsigned(16) ElementType;

//! SiteVisitorByID.ulam:20: 	typedef WindowScanner.Category Category;

//! SiteVisitorByID.ulam:21: 	constant Unsigned cCATEGORY_COUNT = Category.maxof + 1;// XXX Wish it was: WindowScanner.cCATEGORY_COUNT;

//! SiteVisitorByID.ulam:23: 	Seqno mSeqno[cCATEGORY_COUNT];
    typedef UlamRefFixed<EC, 0u, 192u> Up_Um_6mSeqno; //gcnl:NodeVarDeclDM.cpp:1095

//! SiteVisitorByID.ulam:24: 	ID mID[cCATEGORY_COUNT];
    typedef UlamRefFixed<EC, 192u, 320u> Up_Um_3mID; //gcnl:NodeVarDeclDM.cpp:1095

//! SiteVisitorByID.ulam:25: 	ElementType mType[cCATEGORY_COUNT];
    typedef UlamRefFixed<EC, 512u, 512u> Up_Um_5mType; //gcnl:NodeVarDeclDM.cpp:1095

//! SiteVisitorByID.ulam:26: 	Bool mInUse[cCATEGORY_COUNT];
    typedef UlamRefFixed<EC, 1024u, 32u> Up_Um_6mInUse; //gcnl:NodeVarDeclDM.cpp:1095

//! SiteVisitorByID.ulam:27: 	Bool mInvert[cCATEGORY_COUNT];
    typedef UlamRefFixed<EC, 1056u, 32u> Up_Um_7mInvert; //gcnl:NodeVarDeclDM.cpp:1095

//! SiteVisitorByID.ulam:28: 	Bool mNeighbor[cCATEGORY_COUNT];
    typedef UlamRefFixed<EC, 1088u, 32u> Up_Um_919mNeighbor; //gcnl:NodeVarDeclDM.cpp:1095

    void Uf_5reset(const UlamContext<EC>& uc, UlamRef<EC>& ur) const; //gcnl:SymbolFunction.cpp:463

    void Uf_7setType(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Ut_10151u<EC>& Uv_1c, Ui_Ut_102161u<EC>& Uv_2et) const; //gcnl:SymbolFunction.cpp:463

    void Uf_5setID(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Ut_10151u<EC>& Uv_1c, Ui_Ut_102101u<EC>& Uv_2id) const; //gcnl:SymbolFunction.cpp:463

    void Uf_9212neighborCell(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Ut_10151u<EC>& Uv_1c) const; //gcnl:SymbolFunction.cpp:463

    static void Uf_5visit(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Un_r10412489213WindowScanner10<EC>& Ur_4wsrv, Ui_Ut_r102961a<EC>& Ur_1a, Ui_Ut_10161u<EC>& Uv_2sn); //virtual //gcnl:SymbolFunction.cpp:451

    //and its contextual type info for virtual table entries:
    typedef void (* Uf_5visit13r10412489213WindowScanner10r102961a10161u) (const UlamContext<EC>&, UlamRef<EC>& , Ui_Un_r10412489213WindowScanner10<EC>&, Ui_Ut_r102961a<EC>&, Ui_Ut_10161u<EC>&); //gcnl:SymbolFunction.cpp:518
    void Uf_6invert(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Ut_10151u<EC>& Uv_1c) const; //gcnl:SymbolFunction.cpp:463

    void Uf_919unsetType(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Ut_10151u<EC>& Uv_1c) const; //gcnl:SymbolFunction.cpp:463

    void Uf_8setSeqno(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Ut_10151u<EC>& Uv_1c, Ui_Ut_10161u<EC>& Uv_5seqno) const; //gcnl:SymbolFunction.cpp:463

    Ui_Ut_102101u<EC> Uf_5getID(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Ut_10161u<EC>& Uv_2sn) const; //gcnl:SymbolFunction.cpp:463

    Ui_Ut_10161u<EC> Uf_8getSeqno(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Ut_10161u<EC>& Uv_2sn) const; //gcnl:SymbolFunction.cpp:463

    //BUILT-IN FUNCTIONS:

    const UlamClassDataMemberInfo & GetDataMemberInfo(u32 dataMemberNumber) const; //gcnl:NodeBlockClass.cpp:2664

    s32 GetDataMemberCount() const; //gcnl:NodeBlockClass.cpp:2728

    const char * GetMangledClassName() const; //gcnl:NodeBlockClass.cpp:2779

    virtual u32 GetClassLength() const; //gcnl:NodeBlockClass.cpp:1992

    virtual const unsigned char * GetString(u32 sidx) const; //gcnl:NodeBlockClass.cpp:2509

    virtual u32 GetStringLength(u32 sidx) const; //gcnl:NodeBlockClass.cpp:2579

    virtual void getDefaultTransient(u32 pos, BitStorage<EC>& bvsref) const; //gcnl:NodeBlockClass.cpp:2189

    static VfuncPtr m_vtable[3]; //gcnl:NodeBlockClass.cpp:2287
    virtual VfuncPtr getVTableEntry(u32 idx) const; //gcnl:NodeBlockClass.cpp:2291

    //helper method not called directly
    bool internalCMethodImplementingIs(const UlamClass<EC> * cptrarg) const; //gcnl:NodeBlockClass.cpp:1933

  };

  template<class EC>
  Un_10411209215SiteVisitorByID10<EC> Un_10411209215SiteVisitorByID10<EC>::THE_INSTANCE;



} //MFM

#include "Un_10411209215SiteVisitorByID10.tcc"
#endif //UN_10411209215SITEVISITORBYID10_H
