/**                                      -*- mode:C++ -*- */

/***********************         DO NOT EDIT        ******************************
*
* WindowScanner.h - Transient header for ULAM //gcnl:SymbolClass.cpp:750
*
**********************************************************************************
* This code is generated by the ULAM programming language compilation system.
*
* The ULAM programming language compilation system is free software:
* you can redistribute it and/or modify it under the terms of the GNU
* General Public License as published by the Free Software
* Foundation, either version 3 of the License, or (at your option)
* any later version.
*
* The ULAM programming language compilation system is distributed in
* the hope that it will be useful, but WITHOUT ANY WARRANTY; without
* even the implied warranty of MERCHANTABILITY or FITNESS FOR A
* PARTICULAR PURPOSE.  See the GNU General Public License for more
* details.
*
* You should have received a copy of the GNU General Public License
* along with the ULAM programming language compilation system
* software.  If not, see <http://www.gnu.org/licenses/>.
*
* @license GPL-3.0+ <http://spdx.org/licenses/GPL-3.0+>
*/

#ifndef UN_10412489213WINDOWSCANNER10_H
#define UN_10412489213WINDOWSCANNER10_H

#include "UlamDefs.h"
#include "Un_10412489213WindowScanner10_Types.h"
//Forward Defs of other classes: //gcnl:SymbolTableOfClasses.cpp:576
namespace MFM { template <class EC> struct Uq_10106UrSelf10; }  //FORWARD
namespace MFM { template <class EC> struct Ue_10106Primer10; }  //FORWARD
namespace MFM { template <class EC> struct Uq_10106Random10; }  //FORWARD
namespace MFM { template <class EC> struct Uq_10109211EventWindow10; }  //FORWARD
namespace MFM { template <class EC> struct Uq_10104Cell10; }  //FORWARD
namespace MFM { template <class EC> struct Uq_10109212DecisionTree10; }  //FORWARD
namespace MFM { template <class EC> struct Ue_102564Gene10; }  //FORWARD
namespace MFM { template <class EC> struct Ue_10105Empty10; }  //FORWARD
namespace MFM { template <class EC> struct Uq_1010919AtomUtils10; }  //FORWARD
namespace MFM { template <class EC> struct Uq_10104Fail10; }  //FORWARD
namespace MFM { template <class EC> struct Uq_10105MDist10; }  //FORWARD
namespace MFM { template <class EC> struct Uq_102323C2D10; }  //FORWARD
namespace MFM { template <class EC> struct Uq_10109210ColorUtils10; }  //FORWARD
namespace MFM { template <class EC> struct Ue_102717Nucleus10; }  //FORWARD
namespace MFM { template <class EC> struct Uq_10109211ClusterByID10; }  //FORWARD
namespace MFM { template <class EC> struct Uq_1010919SiteUtils10; }  //FORWARD
namespace MFM { template <class EC> struct Un_10411209215SiteVisitorByID10; }  //FORWARD
namespace MFM { template <class EC> struct Ue_102188EggShell10; }  //FORWARD
namespace MFM { template <class EC> struct Uq_10109210DebugUtils10; }  //FORWARD
namespace MFM { template <class EC> struct Uq_10109211SiteVisitor10; }  //FORWARD
namespace MFM { template <class EC> struct Un_102329211OutOfBounds10; }  //FORWARD
namespace MFM { template <class EC> struct Un_1035449217SiteVisitorByType10; }  //FORWARD

namespace MFM{

  template<class EC>
  class Un_10412489213WindowScanner10 : public UlamTransient<EC>  /*, Uq_10106UrSelf10 */  {
    // Extract short names for parameter types
    typedef typename EC::ATOM_CONFIG AC;
    typedef typename AC::ATOM_TYPE T;
    enum { BPA = AC::BITS_PER_ATOM };

    typedef BitVector<BPA> BV; //gcnl:NodeBlockClass.cpp:1621
    typedef BitField<BitVector<BPA>, VD::BITS, T::ATOM_FIRST_STATE_BIT, 0> BFTYP; //gcnl:NodeBlockClass.cpp:1624


  public:

    Un_10412489213WindowScanner10(); //gcnl:NodeBlockClass.cpp:1508
    ~Un_10412489213WindowScanner10(); //gcnl:NodeBlockClass.cpp:1513

    static Un_10412489213WindowScanner10 THE_INSTANCE; //gcnl:NodeBlockClass.cpp:1519

//! WindowScanner.ulam:14:   typedef EventWindow.SiteNum SiteNum;

//! WindowScanner.ulam:17:   MDist mdist;
    typedef Uq_10105MDist10<EC> Ut_Um_5mdist; //offset 0u //gcnl:NodeVarDeclDM.cpp:1065

//! WindowScanner.ulam:18:   Random random;
    typedef Uq_10106Random10<EC> Ut_Um_6random; //offset 0u //gcnl:NodeVarDeclDM.cpp:1065

//! WindowScanner.ulam:19:   DebugUtils debug;
    typedef Uq_10109210DebugUtils10<EC> Ut_Um_5debug; //offset 0u //gcnl:NodeVarDeclDM.cpp:1065

//! WindowScanner.ulam:20:   EventWindow ew;
    typedef Uq_10109211EventWindow10<EC> Ut_Um_2ew; //offset 0u //gcnl:NodeVarDeclDM.cpp:1065

//! WindowScanner.ulam:21:   Fail fail;
    typedef Uq_10104Fail10<EC> Ut_Um_4fail; //offset 0u //gcnl:NodeVarDeclDM.cpp:1065

//! WindowScanner.ulam:23:   typedef Unary(4) Radius;

//! WindowScanner.ulam:24:   typedef Unsigned(5) Category;

//! WindowScanner.ulam:25:   constant Unsigned cCATEGORY_COUNT = Category.maxof + 1;

//! WindowScanner.ulam:29:   SiteNum mSites[cCATEGORY_COUNT];
    typedef UlamRefFixed<EC, 0u, 192u> Up_Um_6mSites; //gcnl:NodeVarDeclDM.cpp:1095

//! WindowScanner.ulam:30:   Unsigned mWeights[cCATEGORY_COUNT];
    typedef UlamRefFixed<EC, 192u, 1024u> Up_Um_8mWeights; //gcnl:NodeVarDeclDM.cpp:1095

//! WindowScanner.ulam:31:   Unsigned mCategoriesInUse;
    typedef UlamRefFixed<EC, 1216u, 32u> Up_Um_9216mCategoriesInUse; //gcnl:NodeVarDeclDM.cpp:1095

    Ui_Uq_102323C2D10<EC> Uf_8getCoord(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Ut_10151u<EC>& Uv_5categ) const; //gcnl:SymbolFunction.cpp:463

    void Uf_9215resetCategories(const UlamContext<EC>& uc, UlamRef<EC>& ur) const; //gcnl:SymbolFunction.cpp:463

    Ui_Ut_10151u<EC> Uf_9216allocateCategory(const UlamContext<EC>& uc, UlamRef<EC>& ur) const; //gcnl:SymbolFunction.cpp:463

    void Uf_4scan(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Uq_r10109211SiteVisitor10<EC>& Ur_7visitor) const; //gcnl:SymbolFunction.cpp:463

    void Uf_4scan(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Uq_r10109211SiteVisitor10<EC>& Ur_7visitor, Ui_Ut_10141y<EC>& Uv_5inner, Ui_Ut_10141y<EC>& Uv_5outer) const; //gcnl:SymbolFunction.cpp:463

    Ui_Ut_10161u<EC> Uf_9210getSiteNum(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Ut_10151u<EC>& Uv_5categ) const; //gcnl:SymbolFunction.cpp:463

    void Uf_3die(const UlamContext<EC>& uc, UlamRef<EC>& ur) const; //gcnl:SymbolFunction.cpp:463

    Ui_Ut_102321u<EC> Uf_9219categoriesAvailable(const UlamContext<EC>& uc, UlamRef<EC>& ur) const; //gcnl:SymbolFunction.cpp:463

    void Uf_8initScan(const UlamContext<EC>& uc, UlamRef<EC>& ur) const; //gcnl:SymbolFunction.cpp:463

    Ui_Ut_10161u<EC> Uf_9210categorize(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Ut_10161u<EC>& Uv_2sn, Ui_Ut_10151u<EC>& Uv_5categ) const; //gcnl:SymbolFunction.cpp:463

    Ui_Ut_10161u<EC> Uf_9210categorize(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Ut_10161u<EC>& Uv_2sn, Ui_Ut_10151u<EC>& Uv_5categ, Ui_Ut_102321u<EC>& Uv_6weight) const; //gcnl:SymbolFunction.cpp:463

    Ui_Ut_102321u<EC> Uf_7getHits(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Ut_10151u<EC>& Uv_5categ) const; //gcnl:SymbolFunction.cpp:463

    //BUILT-IN FUNCTIONS:

    const UlamClassDataMemberInfo & GetDataMemberInfo(u32 dataMemberNumber) const; //gcnl:NodeBlockClass.cpp:2664

    s32 GetDataMemberCount() const; //gcnl:NodeBlockClass.cpp:2728

    const char * GetMangledClassName() const; //gcnl:NodeBlockClass.cpp:2779

    virtual u32 GetClassLength() const; //gcnl:NodeBlockClass.cpp:1992

    virtual const unsigned char * GetString(u32 sidx) const; //gcnl:NodeBlockClass.cpp:2509

    virtual u32 GetStringLength(u32 sidx) const; //gcnl:NodeBlockClass.cpp:2579

    virtual void getDefaultTransient(u32 pos, BitStorage<EC>& bvsref) const; //gcnl:NodeBlockClass.cpp:2189

    static VfuncPtr m_vtable[2]; //gcnl:NodeBlockClass.cpp:2287
    virtual VfuncPtr getVTableEntry(u32 idx) const; //gcnl:NodeBlockClass.cpp:2291

    //helper method not called directly
    bool internalCMethodImplementingIs(const UlamClass<EC> * cptrarg) const; //gcnl:NodeBlockClass.cpp:1933

  };

  template<class EC>
  Un_10412489213WindowScanner10<EC> Un_10412489213WindowScanner10<EC>::THE_INSTANCE;



} //MFM

#include "Un_10412489213WindowScanner10.tcc"
#endif //UN_10412489213WINDOWSCANNER10_H
